-- Generated by Matcha GUI Builder
local Mouse = game.Players.LocalPlayer:GetMouse()

-- MainScreen (Square)
local MainScreen = Drawing.new("Square")
MainScreen.Visible = true
MainScreen.Transparency = 0.35
MainScreen.ZIndex = 10
MainScreen.Color = Color3.fromHex("#c75fec")
MainScreen.Position = Vector2.new(100, 89)
MainScreen.Size = Vector2.new(283, 261)
MainScreen.Filled = true

-- OpenBtm (Keybind)

-- Keybind OpenBtm
local OpenBtm = Drawing.new("Square")
OpenBtm.Visible = true
OpenBtm.Transparency = 1
OpenBtm.Color = Color3.fromHex("#696969")
OpenBtm.Filled = true
OpenBtm.Size = Vector2.new(100, 30)
OpenBtm.Position = Vector2.new(283, 89)
OpenBtm.ZIndex = 20
local OpenBtm_Text = Drawing.new("Text")
OpenBtm_Text.Text = "[ O ]"
OpenBtm_Text.Size = 16
OpenBtm_Text.Center = true
OpenBtm_Text.Outline = true
OpenBtm_Text.Font = 0
OpenBtm_Text.Color = Color3.fromHex("#ffffff")
OpenBtm_Text.Position = OpenBtm.Position + Vector2.new(100/2, 30/2)
OpenBtm_Text.Visible = true
OpenBtm_Text.ZIndex = 22
local OpenBtm_Key = 0x4F
local OpenBtm_IsListening = false

-- SoulCount (Text)
local SoulCount = Drawing.new("Text")
SoulCount.Visible = true
SoulCount.Transparency = 1
SoulCount.ZIndex = 30
SoulCount.Color = Color3.fromHex("#FFFFFF")
SoulCount.Position = Vector2.new(100, 138)
SoulCount.Text = "Soul: "
SoulCount.Size = 22
SoulCount.Center = false
SoulCount.Outline = true
SoulCount.Font = Drawing.Fonts.UI

-- RelictCount (Text)
local RelictCount = Drawing.new("Text")
RelictCount.Visible = true
RelictCount.Transparency = 1
RelictCount.ZIndex = 40
RelictCount.Color = Color3.fromHex("#FFFFFF")
RelictCount.Position = Vector2.new(100, 155)
RelictCount.Text = "Relict: "
RelictCount.Size = 22
RelictCount.Center = false
RelictCount.Outline = true
RelictCount.Font = Drawing.Fonts.UI

-- BibleCount (Text)
local BibleCount = Drawing.new("Text")
BibleCount.Visible = true
BibleCount.Transparency = 1
BibleCount.ZIndex = 50
BibleCount.Color = Color3.fromHex("#FFFFFF")
BibleCount.Position = Vector2.new(100, 174)
BibleCount.Text = "Bible: "
BibleCount.Size = 22
BibleCount.Center = false
BibleCount.Outline = true
BibleCount.Font = Drawing.Fonts.UI

-- FaithCount (Text)
local FaithCount = Drawing.new("Text")
FaithCount.Visible = true
FaithCount.Transparency = 1
FaithCount.ZIndex = 60
FaithCount.Color = Color3.fromHex("#FFFFFF")
FaithCount.Position = Vector2.new(100, 195)
FaithCount.Text = "Faith: "
FaithCount.Size = 22
FaithCount.Center = false
FaithCount.Outline = true
FaithCount.Font = Drawing.Fonts.UI

-- RebirthCount (Text)
local RebirthCount = Drawing.new("Text")
RebirthCount.Visible = true
RebirthCount.Transparency = 1
RebirthCount.ZIndex = 70
RebirthCount.Color = Color3.fromHex("#FFFFFF")
RebirthCount.Position = Vector2.new(100, 217)
RebirthCount.Text = "Rebirth: "
RebirthCount.Size = 22
RebirthCount.Center = false
RebirthCount.Outline = true
RebirthCount.Font = Drawing.Fonts.UI

-- EliteSoulCount (Text)
local EliteSoulCount = Drawing.new("Text")
EliteSoulCount.Visible = true
EliteSoulCount.Transparency = 1
EliteSoulCount.ZIndex = 80
EliteSoulCount.Color = Color3.fromHex("#FFFFFF")
EliteSoulCount.Position = Vector2.new(100, 119)
EliteSoulCount.Text = "Elite Soul: "
EliteSoulCount.Size = 22
EliteSoulCount.Center = false
EliteSoulCount.Outline = true
EliteSoulCount.Font = Drawing.Fonts.UI

-- AutoEliteSoulSwitch (Switch)
local AutoEliteSoulSwitch = Drawing.new("Switch")
AutoEliteSoulSwitch.Visible = true
AutoEliteSoulSwitch.Transparency = 1
AutoEliteSoulSwitch.ZIndex = 90
AutoEliteSoulSwitch.Color = Color3.fromHex("#ecbbea")
AutoEliteSoulSwitch.Position = Vector2.new(100, 240)

-- Switch AutoEliteSoulSwitch
local AutoEliteSoulSwitch_IsChecked = false
local AutoEliteSoulSwitch = Drawing.new("Square")
AutoEliteSoulSwitch.Visible = true
AutoEliteSoulSwitch.Transparency = 1
AutoEliteSoulSwitch.Color = Color3.fromHex("#000000")
AutoEliteSoulSwitch.Thickness = 1
AutoEliteSoulSwitch.Filled = false
AutoEliteSoulSwitch.Size = Vector2.new(40, 20)
AutoEliteSoulSwitch.Position = Vector2.new(100, 240)
AutoEliteSoulSwitch.ZIndex = 90
local AutoEliteSoulSwitch_Bg = Drawing.new("Square")
AutoEliteSoulSwitch_Bg.Visible = true
AutoEliteSoulSwitch_Bg.Transparency = 1
AutoEliteSoulSwitch_Bg.Color = Color3.fromHex("#ecbbea")
AutoEliteSoulSwitch_Bg.Filled = true
AutoEliteSoulSwitch_Bg.Size = AutoEliteSoulSwitch.Size
AutoEliteSoulSwitch_Bg.Position = AutoEliteSoulSwitch.Position
AutoEliteSoulSwitch_Bg.ZIndex = 90
local AutoEliteSoulSwitch_IndBorder = Drawing.new("Square")
AutoEliteSoulSwitch_IndBorder.Visible = true
AutoEliteSoulSwitch_IndBorder.Transparency = 1
AutoEliteSoulSwitch_IndBorder.Color = Color3.fromHex("#000000")
AutoEliteSoulSwitch_IndBorder.Thickness = 1
AutoEliteSoulSwitch_IndBorder.Filled = false
AutoEliteSoulSwitch_IndBorder.Size = Vector2.new(18, 18)
AutoEliteSoulSwitch_IndBorder.ZIndex = 92
local AutoEliteSoulSwitch_Ind = Drawing.new("Square")
AutoEliteSoulSwitch_Ind.Visible = true
AutoEliteSoulSwitch_Ind.Transparency = 1
AutoEliteSoulSwitch_Ind.Color = Color3.fromHex("#000000")
AutoEliteSoulSwitch_Ind.Filled = true
AutoEliteSoulSwitch_Ind.Size = Vector2.new(18, 18)
AutoEliteSoulSwitch_Ind.ZIndex = 92
if AutoEliteSoulSwitch_IsChecked then
    AutoEliteSoulSwitch_IndBorder.Position = AutoEliteSoulSwitch.Position + Vector2.new(21, 1)
    AutoEliteSoulSwitch_Ind.Position = AutoEliteSoulSwitch.Position + Vector2.new(21, 1)
else
    AutoEliteSoulSwitch_IndBorder.Position = AutoEliteSoulSwitch.Position + Vector2.new(1, 1)
    AutoEliteSoulSwitch_Ind.Position = AutoEliteSoulSwitch.Position + Vector2.new(1, 1)
end
local AutoEliteSoulSwitch_Label = Drawing.new("Text")
AutoEliteSoulSwitch_Label.Visible = true
AutoEliteSoulSwitch_Label.Text = "Auto Elite Soul"
AutoEliteSoulSwitch_Label.Size = 16
AutoEliteSoulSwitch_Label.Color = Color3.fromHex("#ffffff")
AutoEliteSoulSwitch_Label.Outline = true
AutoEliteSoulSwitch_Label.Font = Drawing.Fonts.UI
AutoEliteSoulSwitch_Label.Position = AutoEliteSoulSwitch.Position + Vector2.new(50, 2)
AutoEliteSoulSwitch_Label.ZIndex = 91

local KeyNames = {
    [48] = "0",
    [49] = "1",
    [50] = "2",
    [51] = "3",
    [52] = "4",
    [53] = "5",
    [54] = "6",
    [55] = "7",
    [56] = "8",
    [57] = "9",
    [1] = "LeftMouse",
    [2] = "RightMouse",
    [4] = "MiddleMouse",
    [8] = "Backspace",
    [9] = "Tab",
    [13] = "Enter",
    [16] = "Shift",
    [17] = "Ctrl",
    [18] = "Alt",
    [19] = "Pause",
    [20] = "CapsLock",
    [27] = "Esc",
    [32] = "Space",
    [33] = "PageUp",
    [34] = "PageDown",
    [35] = "End",
    [36] = "Home",
    [37] = "Left",
    [38] = "Up",
    [39] = "Right",
    [40] = "Down",
    [45] = "Insert",
    [46] = "Delete",
    [65] = "A",
    [66] = "B",
    [67] = "C",
    [68] = "D",
    [69] = "E",
    [70] = "F",
    [71] = "G",
    [72] = "H",
    [73] = "I",
    [74] = "J",
    [75] = "K",
    [76] = "L",
    [77] = "M",
    [78] = "N",
    [79] = "O",
    [80] = "P",
    [81] = "Q",
    [82] = "R",
    [83] = "S",
    [84] = "T",
    [85] = "U",
    [86] = "V",
    [87] = "W",
    [88] = "X",
    [89] = "Y",
    [90] = "Z",
    [112] = "F1",
    [113] = "F2",
    [114] = "F3",
    [115] = "F4",
    [116] = "F5",
    [117] = "F6",
    [118] = "F7",
    [119] = "F8",
    [120] = "F9",
    [121] = "F10",
    [122] = "F11",
    [123] = "F12",
}

-- Input Handling
local dragging = nil
local dragStart = nil
local startPos = nil
local knobStartPos = nil
local lastMouse1 = false

while true do
    wait(0.01)
    if isrbxactive() then
        local mouse1 = ismouse1pressed()
        local mPos = Vector2.new(Mouse.X, Mouse.Y)

        -- Keybind Listeners
        if OpenBtm_IsListening then
             for i = 1, 255 do
                 if iskeypressed(i) and not ismouse1pressed() then -- Avoid mouse clicks registering as keys if shared ID
                     OpenBtm_Key = i
                     OpenBtm_IsListening = false
                     local keyName = KeyNames[i] or "Unknown"
                     OpenBtm_Text.Text = "[ " .. keyName .. " ]"
                     OpenBtm_Text.Color = Color3.fromHex("#ffffff")
                     pcall(function() onKeyChanged(i) end)
                     wait(0.2) -- Prevent immediate trigger
                     break
                 end
             end
        else
             if iskeypressed(OpenBtm_Key) then
                 -- Intelligent Action
                 local newState = not MainScreen.Visible
                 MainScreen.Visible = newState
                 OpenBtm.Visible = newState
                 OpenBtm_Text.Visible = newState
                 SoulCount.Visible = newState
                 RelictCount.Visible = newState
                 BibleCount.Visible = newState
                 FaithCount.Visible = newState
                 RebirthCount.Visible = newState
                 EliteSoulCount.Visible = newState
                 AutoEliteSoulSwitch.Visible = newState
                 AutoEliteSoulSwitch.Visible = newState
                 AutoEliteSoulSwitch_Bg.Visible = newState
                 AutoEliteSoulSwitch_IndBorder.Visible = newState
                 AutoEliteSoulSwitch_Ind.Visible = newState
                 AutoEliteSoulSwitch_Label.Visible = newState
                 wait(0.2) -- Debounce
             end
        end

        -- Mouse Down (Just Pressed)
        if mouse1 and not lastMouse1 then
            -- Button OpenBtm
            if OpenBtm.Visible and mPos.X >= OpenBtm.Position.X and mPos.X <= OpenBtm.Position.X + OpenBtm.Size.X and
               mPos.Y >= OpenBtm.Position.Y and mPos.Y <= OpenBtm.Position.Y + OpenBtm.Size.Y then
                pcall(function() onKeyChanged() end)
                -- Keybind Click
                OpenBtm_IsListening = true
                OpenBtm_Text.Text = "..."
                OpenBtm_Text.Color = Color3.fromHex("#FFFF00")
            end
            -- Button AutoEliteSoulSwitch
            if AutoEliteSoulSwitch_Label.Visible and mPos.X >= AutoEliteSoulSwitch.Position.X and mPos.X <= AutoEliteSoulSwitch.Position.X + AutoEliteSoulSwitch.Size.X and
               mPos.Y >= AutoEliteSoulSwitch.Position.Y and mPos.Y <= AutoEliteSoulSwitch.Position.Y + AutoEliteSoulSwitch.Size.Y then
                -- Toggle Switch
                AutoEliteSoulSwitch_IsChecked = not AutoEliteSoulSwitch_IsChecked
                if AutoEliteSoulSwitch_IsChecked then
                    AutoEliteSoulSwitch_IndBorder.Position = AutoEliteSoulSwitch.Position + Vector2.new(21, 1)
                    AutoEliteSoulSwitch_Ind.Position = AutoEliteSoulSwitch.Position + Vector2.new(21, 1)
                else
                    AutoEliteSoulSwitch_IndBorder.Position = AutoEliteSoulSwitch.Position + Vector2.new(1, 1)
                    AutoEliteSoulSwitch_Ind.Position = AutoEliteSoulSwitch.Position + Vector2.new(1, 1)
                end
                if onSwitch then pcall(function() onSwitch(AutoEliteSoulSwitch_IsChecked) end) end
            end
        end

        -- Mouse Up (Just Released)
        if not mouse1 and lastMouse1 then
            dragging = nil
        end

        -- Dragging Update
        if dragging and mouse1 then
            local delta = mPos - dragStart
            dragging.Position = startPos + delta
        end

        lastMouse1 = mouse1
    end
end
